language: java

jdk:
  - oraclejdk8
  - oraclejdk10
  - oraclejdk-ea
  - openjdk10
  - openjdk11

services:
  - mongodb
  - redis
install: true

script:
  - ./mvnw clean package
before_cache:
  - rm -fr  $HOME/.embedmongo
  - rm -fr  $HOME/.m2
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.embedmongo'
    
after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)