language: java

jdk:
  - oraclejdk10

services:
  - mongodb
  - redis
  - postgresql
  
install: true

before_script:
  - sleep 15
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - ./mvnw clean verify -P travis
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.embedmongo'
    
after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)