language: java

jdk:
  - oraclejdk8
  - oraclejdk10

services:
  - mongodb
  - redis
install: true

script:
  - ./mvnw clean package
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.embedmongo'
    
after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)