language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - redis
install: true
script:
  - mvn clean verify
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.embedmongo'
    
after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)