/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables.records;


import com.poc.restfulpoc.jooq.tables.Address;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> implements Record5<Long, String, String, String, String> {

    private static final long serialVersionUID = -629401018;

    /**
     * Setter for <code>PUBLIC.ADDRESS.CUSTOMER_ID</code>.
     */
    public void setCustomerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.CUSTOMER_ID</code>.
     */
    public Long getCustomerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.COUNTY</code>.
     */
    public void setCounty(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.COUNTY</code>.
     */
    public String getCounty() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.POSTCODE</code>.
     */
    public void setPostcode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.POSTCODE</code>.
     */
    public String getPostcode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.STREET</code>.
     */
    public void setStreet(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.STREET</code>.
     */
    public String getStreet() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ADDRESS.TOWN</code>.
     */
    public void setTown(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ADDRESS.TOWN</code>.
     */
    public String getTown() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Address.ADDRESS.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Address.ADDRESS.COUNTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Address.ADDRESS.POSTCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Address.ADDRESS.STREET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Address.ADDRESS.TOWN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCounty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPostcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCounty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPostcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value1(Long value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value2(String value) {
        setCounty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value3(String value) {
        setPostcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value4(String value) {
        setStreet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value5(String value) {
        setTown(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord values(Long value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Long customerId, String county, String postcode, String street, String town) {
        super(Address.ADDRESS);

        set(0, customerId);
        set(1, county);
        set(2, postcode);
        set(3, street);
        set(4, town);
    }
}
