/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables.records;


import com.poc.restfulpoc.jooq.tables.Orders;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> implements Record5<Long, Timestamp, String, String, Long> {

    private static final long serialVersionUID = 903065956;

    /**
     * Setter for <code>PUBLIC.ORDERS.ORDER_ID</code>.
     */
    public void setOrderId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.ORDER_ID</code>.
     */
    public Long getOrderId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.CREATED_ON</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.CREATED_ON</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.ORDER_NUMBER</code>.
     */
    public void setOrderNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.ORDER_NUMBER</code>.
     */
    public String getOrderNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.STATUS</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.CUSTOMER_ID</code>.
     */
    public void setCustomerId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.CUSTOMER_ID</code>.
     */
    public Long getCustomerId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Timestamp, String, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Timestamp, String, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Orders.ORDERS.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Orders.ORDERS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Orders.ORDERS.ORDER_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Orders.ORDERS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Orders.ORDERS.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrderNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrderNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value1(Long value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value2(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value3(String value) {
        setOrderNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value5(Long value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord values(Long value1, Timestamp value2, String value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Long orderId, Timestamp createdOn, String orderNumber, String status, Long customerId) {
        super(Orders.ORDERS);

        set(0, orderId);
        set(1, createdOn);
        set(2, orderNumber);
        set(3, status);
        set(4, customerId);
    }
}
