/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables.records;


import com.poc.restfulpoc.jooq.tables.PostDetails;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostDetailsRecord extends UpdatableRecordImpl<PostDetailsRecord> implements Record3<String, Timestamp, Long> {

    private static final long serialVersionUID = -518152461;

    /**
     * Setter for <code>PUBLIC.POST_DETAILS.CREATED_BY</code>.
     */
    public void setCreatedBy(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.POST_DETAILS.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.POST_DETAILS.CREATED_ON</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.POST_DETAILS.CREATED_ON</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>PUBLIC.POST_DETAILS.POST_ID</code>.
     */
    public void setPostId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.POST_DETAILS.POST_ID</code>.
     */
    public Long getPostId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PostDetails.POST_DETAILS.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return PostDetails.POST_DETAILS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PostDetails.POST_DETAILS.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsRecord value1(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsRecord value2(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsRecord value3(Long value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsRecord values(String value1, Timestamp value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostDetailsRecord
     */
    public PostDetailsRecord() {
        super(PostDetails.POST_DETAILS);
    }

    /**
     * Create a detached, initialised PostDetailsRecord
     */
    public PostDetailsRecord(String createdBy, Timestamp createdOn, Long postId) {
        super(PostDetails.POST_DETAILS);

        set(0, createdBy);
        set(1, createdOn);
        set(2, postId);
    }
}
