/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables.records;


import com.poc.restfulpoc.jooq.tables.PostComment;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostCommentRecord extends UpdatableRecordImpl<PostCommentRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = -20561004;

    /**
     * Setter for <code>PUBLIC.POST_COMMENT.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.POST_COMMENT.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.POST_COMMENT.REVIEW</code>.
     */
    public void setReview(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.POST_COMMENT.REVIEW</code>.
     */
    public String getReview() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.POST_COMMENT.POST_ID</code>.
     */
    public void setPostId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.POST_COMMENT.POST_ID</code>.
     */
    public Long getPostId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PostComment.POST_COMMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PostComment.POST_COMMENT.REVIEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PostComment.POST_COMMENT.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReview();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReview();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentRecord value2(String value) {
        setReview(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentRecord value3(Long value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostCommentRecord
     */
    public PostCommentRecord() {
        super(PostComment.POST_COMMENT);
    }

    /**
     * Create a detached, initialised PostCommentRecord
     */
    public PostCommentRecord(Long id, String review, Long postId) {
        super(PostComment.POST_COMMENT);

        set(0, id);
        set(1, review);
        set(2, postId);
    }
}
