/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables.records;


import com.poc.restfulpoc.jooq.tables.PostTag;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostTagRecord extends TableRecordImpl<PostTagRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 933114659;

    /**
     * Setter for <code>PUBLIC.POST_TAG.POST_ID</code>.
     */
    public void setPostId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.POST_TAG.POST_ID</code>.
     */
    public Long getPostId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.POST_TAG.TAG_ID</code>.
     */
    public void setTagId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.POST_TAG.TAG_ID</code>.
     */
    public Long getTagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PostTag.POST_TAG.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PostTag.POST_TAG.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostTagRecord value1(Long value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostTagRecord value2(Long value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostTagRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostTagRecord
     */
    public PostTagRecord() {
        super(PostTag.POST_TAG);
    }

    /**
     * Create a detached, initialised PostTagRecord
     */
    public PostTagRecord(Long postId, Long tagId) {
        super(PostTag.POST_TAG);

        set(0, postId);
        set(1, tagId);
    }
}
