/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq;


import com.poc.restfulpoc.jooq.tables.Address;
import com.poc.restfulpoc.jooq.tables.Customer;
import com.poc.restfulpoc.jooq.tables.Orders;
import com.poc.restfulpoc.jooq.tables.Post;
import com.poc.restfulpoc.jooq.tables.PostComment;
import com.poc.restfulpoc.jooq.tables.PostDetails;
import com.poc.restfulpoc.jooq.tables.PostTag;
import com.poc.restfulpoc.jooq.tables.Tag;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_E = Indexes0.PRIMARY_KEY_E;
    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;
    public static final Index FKBHAWAVFSVMODCHTKO734A1YTI_INDEX_8 = Indexes0.FKBHAWAVFSVMODCHTKO734A1YTI_INDEX_8;
    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index UK_NTHKIU7PGMNQNU86I2JYOE2V7_INDEX_8 = Indexes0.UK_NTHKIU7PGMNQNU86I2JYOE2V7_INDEX_8;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index FKNA4Y825FDC5HW8AOW65IJEXM0_INDEX_2 = Indexes0.FKNA4Y825FDC5HW8AOW65IJEXM0_INDEX_2;
    public static final Index PRIMARY_KEY_24 = Indexes0.PRIMARY_KEY_24;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;
    public static final Index FKAC1WDCHD2PNUR3FL225OBMLG0_INDEX_5 = Indexes0.FKAC1WDCHD2PNUR3FL225OBMLG0_INDEX_5;
    public static final Index FKC2AUETUVSEC0K566L0EYVR9CS_INDEX_5 = Indexes0.FKC2AUETUVSEC0K566L0EYVR9CS_INDEX_5;
    public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_E = Internal.createIndex("PRIMARY_KEY_E", Address.ADDRESS, new OrderField[] { Address.ADDRESS.CUSTOMER_ID }, true);
        public static Index PRIMARY_KEY_5 = Internal.createIndex("PRIMARY_KEY_5", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index FKBHAWAVFSVMODCHTKO734A1YTI_INDEX_8 = Internal.createIndex("FKBHAWAVFSVMODCHTKO734A1YTI_INDEX_8", Orders.ORDERS, new OrderField[] { Orders.ORDERS.CUSTOMER_ID }, false);
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ORDER_ID }, true);
        public static Index UK_NTHKIU7PGMNQNU86I2JYOE2V7_INDEX_8 = Internal.createIndex("UK_NTHKIU7PGMNQNU86I2JYOE2V7_INDEX_8", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ORDER_NUMBER }, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", Post.POST, new OrderField[] { Post.POST.ID }, true);
        public static Index FKNA4Y825FDC5HW8AOW65IJEXM0_INDEX_2 = Internal.createIndex("FKNA4Y825FDC5HW8AOW65IJEXM0_INDEX_2", PostComment.POST_COMMENT, new OrderField[] { PostComment.POST_COMMENT.POST_ID }, false);
        public static Index PRIMARY_KEY_24 = Internal.createIndex("PRIMARY_KEY_24", PostComment.POST_COMMENT, new OrderField[] { PostComment.POST_COMMENT.ID }, true);
        public static Index PRIMARY_KEY_4 = Internal.createIndex("PRIMARY_KEY_4", PostDetails.POST_DETAILS, new OrderField[] { PostDetails.POST_DETAILS.POST_ID }, true);
        public static Index FKAC1WDCHD2PNUR3FL225OBMLG0_INDEX_5 = Internal.createIndex("FKAC1WDCHD2PNUR3FL225OBMLG0_INDEX_5", PostTag.POST_TAG, new OrderField[] { PostTag.POST_TAG.TAG_ID }, false);
        public static Index FKC2AUETUVSEC0K566L0EYVR9CS_INDEX_5 = Internal.createIndex("FKC2AUETUVSEC0K566L0EYVR9CS_INDEX_5", PostTag.POST_TAG, new OrderField[] { PostTag.POST_TAG.POST_ID }, false);
        public static Index PRIMARY_KEY_1 = Internal.createIndex("PRIMARY_KEY_1", Tag.TAG, new OrderField[] { Tag.TAG.ID }, true);
    }
}
