/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq;


import com.poc.restfulpoc.jooq.tables.Address;
import com.poc.restfulpoc.jooq.tables.Customer;
import com.poc.restfulpoc.jooq.tables.Orders;
import com.poc.restfulpoc.jooq.tables.Post;
import com.poc.restfulpoc.jooq.tables.PostComment;
import com.poc.restfulpoc.jooq.tables.PostDetails;
import com.poc.restfulpoc.jooq.tables.PostTag;
import com.poc.restfulpoc.jooq.tables.Tag;
import com.poc.restfulpoc.jooq.tables.records.AddressRecord;
import com.poc.restfulpoc.jooq.tables.records.CustomerRecord;
import com.poc.restfulpoc.jooq.tables.records.OrdersRecord;
import com.poc.restfulpoc.jooq.tables.records.PostCommentRecord;
import com.poc.restfulpoc.jooq.tables.records.PostDetailsRecord;
import com.poc.restfulpoc.jooq.tables.records.PostRecord;
import com.poc.restfulpoc.jooq.tables.records.PostTagRecord;
import com.poc.restfulpoc.jooq.tables.records.TagRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AddressRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
    public static final UniqueKey<CustomerRecord> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;
    public static final UniqueKey<OrdersRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<OrdersRecord> UK_NTHKIU7PGMNQNU86I2JYOE2V7 = UniqueKeys0.UK_NTHKIU7PGMNQNU86I2JYOE2V7;
    public static final UniqueKey<PostRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<PostCommentRecord> CONSTRAINT_24 = UniqueKeys0.CONSTRAINT_24;
    public static final UniqueKey<PostDetailsRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<TagRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AddressRecord, CustomerRecord> FKC90HQ90Y53KIV2106TSFR0PM8 = ForeignKeys0.FKC90HQ90Y53KIV2106TSFR0PM8;
    public static final ForeignKey<OrdersRecord, CustomerRecord> FKBHAWAVFSVMODCHTKO734A1YTI = ForeignKeys0.FKBHAWAVFSVMODCHTKO734A1YTI;
    public static final ForeignKey<PostCommentRecord, PostRecord> FKNA4Y825FDC5HW8AOW65IJEXM0 = ForeignKeys0.FKNA4Y825FDC5HW8AOW65IJEXM0;
    public static final ForeignKey<PostDetailsRecord, PostRecord> FKMCGDM1K7IRIYXSQ4KUKEBJ4EI = ForeignKeys0.FKMCGDM1K7IRIYXSQ4KUKEBJ4EI;
    public static final ForeignKey<PostTagRecord, PostRecord> FKC2AUETUVSEC0K566L0EYVR9CS = ForeignKeys0.FKC2AUETUVSEC0K566L0EYVR9CS;
    public static final ForeignKey<PostTagRecord, TagRecord> FKAC1WDCHD2PNUR3FL225OBMLG0 = ForeignKeys0.FKAC1WDCHD2PNUR3FL225OBMLG0;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AddressRecord> CONSTRAINT_E = Internal.createUniqueKey(Address.ADDRESS, "CONSTRAINT_E", Address.ADDRESS.CUSTOMER_ID);
        public static final UniqueKey<CustomerRecord> CONSTRAINT_5 = Internal.createUniqueKey(Customer.CUSTOMER, "CONSTRAINT_5", Customer.CUSTOMER.ID);
        public static final UniqueKey<OrdersRecord> CONSTRAINT_8 = Internal.createUniqueKey(Orders.ORDERS, "CONSTRAINT_8", Orders.ORDERS.ORDER_ID);
        public static final UniqueKey<OrdersRecord> UK_NTHKIU7PGMNQNU86I2JYOE2V7 = Internal.createUniqueKey(Orders.ORDERS, "UK_NTHKIU7PGMNQNU86I2JYOE2V7", Orders.ORDERS.ORDER_NUMBER);
        public static final UniqueKey<PostRecord> CONSTRAINT_2 = Internal.createUniqueKey(Post.POST, "CONSTRAINT_2", Post.POST.ID);
        public static final UniqueKey<PostCommentRecord> CONSTRAINT_24 = Internal.createUniqueKey(PostComment.POST_COMMENT, "CONSTRAINT_24", PostComment.POST_COMMENT.ID);
        public static final UniqueKey<PostDetailsRecord> CONSTRAINT_4 = Internal.createUniqueKey(PostDetails.POST_DETAILS, "CONSTRAINT_4", PostDetails.POST_DETAILS.POST_ID);
        public static final UniqueKey<TagRecord> CONSTRAINT_1 = Internal.createUniqueKey(Tag.TAG, "CONSTRAINT_1", Tag.TAG.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AddressRecord, CustomerRecord> FKC90HQ90Y53KIV2106TSFR0PM8 = Internal.createForeignKey(com.poc.restfulpoc.jooq.Keys.CONSTRAINT_5, Address.ADDRESS, "FKC90HQ90Y53KIV2106TSFR0PM8", Address.ADDRESS.CUSTOMER_ID);
        public static final ForeignKey<OrdersRecord, CustomerRecord> FKBHAWAVFSVMODCHTKO734A1YTI = Internal.createForeignKey(com.poc.restfulpoc.jooq.Keys.CONSTRAINT_5, Orders.ORDERS, "FKBHAWAVFSVMODCHTKO734A1YTI", Orders.ORDERS.CUSTOMER_ID);
        public static final ForeignKey<PostCommentRecord, PostRecord> FKNA4Y825FDC5HW8AOW65IJEXM0 = Internal.createForeignKey(com.poc.restfulpoc.jooq.Keys.CONSTRAINT_2, PostComment.POST_COMMENT, "FKNA4Y825FDC5HW8AOW65IJEXM0", PostComment.POST_COMMENT.POST_ID);
        public static final ForeignKey<PostDetailsRecord, PostRecord> FKMCGDM1K7IRIYXSQ4KUKEBJ4EI = Internal.createForeignKey(com.poc.restfulpoc.jooq.Keys.CONSTRAINT_2, PostDetails.POST_DETAILS, "FKMCGDM1K7IRIYXSQ4KUKEBJ4EI", PostDetails.POST_DETAILS.POST_ID);
        public static final ForeignKey<PostTagRecord, PostRecord> FKC2AUETUVSEC0K566L0EYVR9CS = Internal.createForeignKey(com.poc.restfulpoc.jooq.Keys.CONSTRAINT_2, PostTag.POST_TAG, "FKC2AUETUVSEC0K566L0EYVR9CS", PostTag.POST_TAG.POST_ID);
        public static final ForeignKey<PostTagRecord, TagRecord> FKAC1WDCHD2PNUR3FL225OBMLG0 = Internal.createForeignKey(com.poc.restfulpoc.jooq.Keys.CONSTRAINT_1, PostTag.POST_TAG, "FKAC1WDCHD2PNUR3FL225OBMLG0", PostTag.POST_TAG.TAG_ID);
    }
}
