/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq;


import com.poc.restfulpoc.jooq.tables.Address;
import com.poc.restfulpoc.jooq.tables.Customer;
import com.poc.restfulpoc.jooq.tables.Orders;
import com.poc.restfulpoc.jooq.tables.Post;
import com.poc.restfulpoc.jooq.tables.PostComment;
import com.poc.restfulpoc.jooq.tables.PostDetails;
import com.poc.restfulpoc.jooq.tables.PostTag;
import com.poc.restfulpoc.jooq.tables.Tag;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 380911477;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ADDRESS</code>.
     */
    public final Address ADDRESS = com.poc.restfulpoc.jooq.tables.Address.ADDRESS;

    /**
     * The table <code>PUBLIC.CUSTOMER</code>.
     */
    public final Customer CUSTOMER = com.poc.restfulpoc.jooq.tables.Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.ORDERS</code>.
     */
    public final Orders ORDERS = com.poc.restfulpoc.jooq.tables.Orders.ORDERS;

    /**
     * The table <code>PUBLIC.POST</code>.
     */
    public final Post POST = com.poc.restfulpoc.jooq.tables.Post.POST;

    /**
     * The table <code>PUBLIC.POST_COMMENT</code>.
     */
    public final PostComment POST_COMMENT = com.poc.restfulpoc.jooq.tables.PostComment.POST_COMMENT;

    /**
     * The table <code>PUBLIC.POST_DETAILS</code>.
     */
    public final PostDetails POST_DETAILS = com.poc.restfulpoc.jooq.tables.PostDetails.POST_DETAILS;

    /**
     * The table <code>PUBLIC.POST_TAG</code>.
     */
    public final PostTag POST_TAG = com.poc.restfulpoc.jooq.tables.PostTag.POST_TAG;

    /**
     * The table <code>PUBLIC.TAG</code>.
     */
    public final Tag TAG = com.poc.restfulpoc.jooq.tables.Tag.TAG;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HIBERNATE_SEQUENCE);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Customer.CUSTOMER,
            Orders.ORDERS,
            Post.POST,
            PostComment.POST_COMMENT,
            PostDetails.POST_DETAILS,
            PostTag.POST_TAG,
            Tag.TAG);
    }
}
