cxf:
  jaxrs:
    classes-scan-packages: org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics
    component-scan: true
  path: /services
logging:
  level:
    com:
      poc:
        restfulpoc: debug
spring:
  activemq:
    in-memory: true
  ## Flyway database Configuration
  flyway:
    baseline-on-migrate: true
  ## Only for Dev environment
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
    ## Enable Hibernate Batching
      hibernate:
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
  cache:
    type: CAFFEINE
    caffeine:
      spec: maximumSize=200,expireAfterAccess=600s
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
     