/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = 1646509978;

    private Long   customerId;
    private String county;
    private String postcode;
    private String street;
    private String town;

    public Address() {}

    public Address(Address value) {
        this.customerId = value.customerId;
        this.county = value.county;
        this.postcode = value.postcode;
        this.street = value.street;
        this.town = value.town;
    }

    public Address(
        Long   customerId,
        String county,
        String postcode,
        String street,
        String town
    ) {
        this.customerId = customerId;
        this.county = county;
        this.postcode = postcode;
        this.street = street;
        this.town = town;
    }

    public Long getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getCounty() {
        return this.county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getTown() {
        return this.town;
    }

    public void setTown(String town) {
        this.town = town;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(customerId);
        sb.append(", ").append(county);
        sb.append(", ").append(postcode);
        sb.append(", ").append(street);
        sb.append(", ").append(town);

        sb.append(")");
        return sb.toString();
    }
}
