/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements Serializable {

    private static final long serialVersionUID = -1204956075;

    private Long      orderId;
    private Timestamp createdOn;
    private String    orderNumber;
    private String    status;
    private Long      customerId;

    public Orders() {}

    public Orders(Orders value) {
        this.orderId = value.orderId;
        this.createdOn = value.createdOn;
        this.orderNumber = value.orderNumber;
        this.status = value.status;
        this.customerId = value.customerId;
    }

    public Orders(
        Long      orderId,
        Timestamp createdOn,
        String    orderNumber,
        String    status,
        Long      customerId
    ) {
        this.orderId = orderId;
        this.createdOn = createdOn;
        this.orderNumber = orderNumber;
        this.status = status;
        this.customerId = customerId;
    }

    public Long getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public String getOrderNumber() {
        return this.orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(orderId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(orderNumber);
        sb.append(", ").append(status);
        sb.append(", ").append(customerId);

        sb.append(")");
        return sb.toString();
    }
}
