/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostComment implements Serializable {

    private static final long serialVersionUID = -2104648857;

    private Long   id;
    private String review;
    private Long   postId;

    public PostComment() {}

    public PostComment(PostComment value) {
        this.id = value.id;
        this.review = value.review;
        this.postId = value.postId;
    }

    public PostComment(
        Long   id,
        String review,
        Long   postId
    ) {
        this.id = id;
        this.review = review;
        this.postId = postId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getReview() {
        return this.review;
    }

    public void setReview(String review) {
        this.review = review;
    }

    public Long getPostId() {
        return this.postId;
    }

    public void setPostId(Long postId) {
        this.postId = postId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PostComment (");

        sb.append(id);
        sb.append(", ").append(review);
        sb.append(", ").append(postId);

        sb.append(")");
        return sb.toString();
    }
}
