/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostTag implements Serializable {

    private static final long serialVersionUID = -2053229115;

    private Long postId;
    private Long tagId;

    public PostTag() {}

    public PostTag(PostTag value) {
        this.postId = value.postId;
        this.tagId = value.tagId;
    }

    public PostTag(
        Long postId,
        Long tagId
    ) {
        this.postId = postId;
        this.tagId = tagId;
    }

    public Long getPostId() {
        return this.postId;
    }

    public void setPostId(Long postId) {
        this.postId = postId;
    }

    public Long getTagId() {
        return this.tagId;
    }

    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PostTag (");

        sb.append(postId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
