/*
 * This file is generated by jOOQ.
*/
package com.poc.restfulpoc.jooq.tables;


import com.poc.restfulpoc.jooq.Indexes;
import com.poc.restfulpoc.jooq.Keys;
import com.poc.restfulpoc.jooq.Public;
import com.poc.restfulpoc.jooq.tables.records.PostDetailsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostDetails extends TableImpl<PostDetailsRecord> {

    private static final long serialVersionUID = -1882122549;

    /**
     * The reference instance of <code>PUBLIC.POST_DETAILS</code>
     */
    public static final PostDetails POST_DETAILS = new PostDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostDetailsRecord> getRecordType() {
        return PostDetailsRecord.class;
    }

    /**
     * The column <code>PUBLIC.POST_DETAILS.CREATED_BY</code>.
     */
    public final TableField<PostDetailsRecord, String> CREATED_BY = createField("CREATED_BY", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.POST_DETAILS.CREATED_ON</code>.
     */
    public final TableField<PostDetailsRecord, Timestamp> CREATED_ON = createField("CREATED_ON", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.POST_DETAILS.POST_ID</code>.
     */
    public final TableField<PostDetailsRecord, Long> POST_ID = createField("POST_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.POST_DETAILS</code> table reference
     */
    public PostDetails() {
        this(DSL.name("POST_DETAILS"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.POST_DETAILS</code> table reference
     */
    public PostDetails(String alias) {
        this(DSL.name(alias), POST_DETAILS);
    }

    /**
     * Create an aliased <code>PUBLIC.POST_DETAILS</code> table reference
     */
    public PostDetails(Name alias) {
        this(alias, POST_DETAILS);
    }

    private PostDetails(Name alias, Table<PostDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostDetails(Name alias, Table<PostDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostDetailsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostDetailsRecord>> getKeys() {
        return Arrays.<UniqueKey<PostDetailsRecord>>asList(Keys.CONSTRAINT_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PostDetailsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PostDetailsRecord, ?>>asList(Keys.FKMCGDM1K7IRIYXSQ4KUKEBJ4EI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetails as(String alias) {
        return new PostDetails(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetails as(Name alias) {
        return new PostDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostDetails rename(String name) {
        return new PostDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostDetails rename(Name name) {
        return new PostDetails(name, null);
    }
}
